version: '3'

services:

  app:
    build:
      context: './www'
    ports:
      - '80:80'
    volumes:
      - './www:/usr/share/nginx/html'

  # upload:
  #   image: tmvdl/node:surge
  #   working_dir: '/app'
  #   volumes:
  #     - '.:/app'
